spring:
  application:
    name: webflux-course
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD:123}@webfluxcourse.ceyztmz.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&ssl=true
      auto-index-creation: true
